theme = "tokyonight_storm"


[editor]
mouse=false
bufferline="multiple"

[editor.whitespace.render]
space="none"
tab="all"
newline="none"
nbsp="all"

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.lsp]
display-inlay-hints=true

[editor.indent-guides]
render=true
character="â”†"
skip-levels=1


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]